### ISSUE TITLE
how to use this lib to interact with a webassembly lib like photon_rs for example

### ISSUE THREAD

**Issue by insinfo** [EPNW/web_ffi#1]
how to use this lib to interact with a webassembly lib like photon_rs for example

I have an AngularDart project and I need to interact with the "photon" lib to resize and compress images before uploading

https://github.com/insinfo/photon-test/blob/master/pkg/photon_rs_bg.wasm
https://github.com/insinfo/photon-test
https://silvia-odwyer.github.io/photon/

**Comment by EPNW** [comment]
Hm I guess not at all. You would use web_ffi if you had normal dart:ffi code and just replace the import. You dont seem to have dart:ffi code in your library.
