### ISSUE TITLE
Error: Bad state: CRITICAL EXCEPTION! Address double use!

### ISSUE THREAD

**Issue by xiaoqunSun** [EPNW/web_ffi#5]
Error: Bad state: CRITICAL EXCEPTION! Address double use! This should never happen, please report this
issue on github immediately at https://github.com/EPNW/web_ffi
Original: [tableIndex=1024	name=__isoc99_vsscanf	argumentCount=3	function=Closure: LegacyJavaScriptObject
from: function 1024() { [native code] }]
Tried: [address=1024	name=__dso_handle]
    at Object.throw_ [as throw] (http://localhost:54626/dart_sdk.js:5067:11)
    at EmscriptenModule._fromJs
    (http://localhost:54626/packages/web_ffi/src/modules/emscripten/emscripten_module.dart.lib.js:96:29)
    at compile
    (http://localhost:54626/packages/web_ffi/src/modules/emscripten/emscripten_module.dart.lib.js:69:53)
    at compile.next (<anonymous>)
    at http://localhost:54626/dart_sdk.js:40571:33
    at _RootZone.runUnary (http://localhost:54626/dart_sdk.js:40441:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:54626/dart_sdk.js:35363:29)
    at handleValueCallback (http://localhost:54626/dart_sdk.js:35931:49)
    at _Future._propagateToListeners (http://localhost:54626/dart_sdk.js:35969:17)
    at [_completeWithValue] (http://localhost:54626/dart_sdk.js:35817:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:54626/dart_sdk.js:35838:35)
    at Object._microtaskLoop (http://localhost:54626/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:54626/dart_sdk.js:40714:13)

maybe in cpp function. use printf

**Comment by EP-u-NW** [comment]
It seems that in the exports of the module, the same address is used for a function and for a global symbol. That's strange...

Did you follow the stepts in https://github.com/EPNW/web_ffi/blob/master/example/README.md to compile your native code or did you do something else?
Can you share the output of the compilation (specifically the `.js` file) for further investigation?
What type of native code did you try to compile? Can you provide it?

**Comment by xiaoqunSun** [comment]
make cmd : 
```shell
emcc -O3 -s MAIN_MODULE=1 -s EXPORT_NAME=algorithm -s MODULARIZE=1 main.cc -o algorithm.js
```
main.cc:
```cpp
#include <stdlib.h>
extern "C" 
{ 
	const char *opus_get_version_string(void)
	{
		return "asdafdfad";
	}

	int *multiply(int a, int b)
	{
		// Allocates native memory in C.
		int *mult = (int *)malloc(sizeof(int));
		*mult = a * b;
		return mult;
	}

	void free_pointer(int *int_pointer)
	{
		// Free native memory in C which was allocated in C.
		free(int_pointer);
	}

}
```

**Comment by EP-u-NW** [comment]
Can you also post your `algorithm.js`? It should contain the symbol table which is helpfull for further analysis. You can upload it as file right to this issue.

In the meantime I will try to compile your code and reproduce the issue.

**Comment by xiaoqunSun** [comment]
[algorithm.js.zip](https://github.com/EPNW/web_ffi/files/8947629/algorithm.js.zip)

**Comment by xiaoqunSun** [comment]
....

**Comment by EP-u-NW** [comment]
I haven't found the issue yet but tried to compile the code you posted on my machine. Can you try this and tell if the error still happens?
[algorithm.zip](https://github.com/EPNW/web_ffi/files/8947918/algorithm.zip)

**Comment by xiaoqunSun** [comment]
the zip works fine

Is it a problem with the emcc version?

my emcc vestion

```shell
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.13
clang version 13.0.0 (/opt/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 8d7cbcf582c5c7bc08a9de7f31fed63bf2687127)

```

**Comment by EP-u-NW** [comment]
Hm can't tell yet... I used docker to build the files using
```Dockerfile
#Uses 3.1.14
FROM emscripten/emsdk

COPY main.cc main.cc

#Not sure if this is needed, just keept it in the Dockerfile from tutorial
RUN apt-get update \
	&& DEBIAN_FRONTENTD="noninteractive" apt-get install -y --no-install-recommends \
	autoconf \
	libtool \
	automake

RUN emcc -O3 -s MAIN_MODULE=1 -s EXPORT_NAME=algorithm -s MODULARIZE=1 main.cc -o algorithm.js
```
Then, I run the container and copy the compiled files out.

It will take some time for me to find the real issue, I hope this solution (either building with Docker or using the zip) will be a sufficient workaround for you...

**Comment by xiaoqunSun** [comment]
problem solved
Upgrade emsdk to 3.1.14
