### ISSUE TITLE
Does not work in a plugin.

### ISSUE THREAD

**Issue by darkstarx** [EPNW/web_ffi#9]
If I place .js and .wasm files in the plugin's assets (the path becomes `packages/myplugin/assets/libmy.js`) then it stucks on the line ´await js.importLibrary('packages/myplugin/assets/libmy.js');´

But if I place the same files in the app's assets, the line `await js.importLibrary('assets/libmy.js');` successfully executed.

**Comment by EP-u-NW** [comment]
Hm interesting... I looked up the implementation in [`opus_flutter_web`](https://github.com/EPNW/opus_flutter/tree/master/opus_flutter_web) and there the following is done:
https://github.com/EPNW/opus_flutter/blob/382a9139482aa4c6f26ea10af146b9564f1f90c3/opus_flutter_web/lib/opus_flutter_web.dart#L27-L28

Can you try using `await js.importLibrary('./assets/packages/myplugin/assets/libmy.js');` and report back? Maybe I need to update the example.

**Comment by darkstarx** [comment]
Sorry, that was my mistake, guys.
To use assets in a plugin you must put them under the `lib` folder and write path to them in the `pubspec.yaml` like
```yaml
assets:
  - packages/my/assets/libmy.js
  - packages/my/assets/libmy.wasm
```
---
Another solution that works in debug and release modes:
1. Put the assets under the root folder of plugin
```
- project_root
  - assets
    - libmy.js
    - libmy.wasm
  - lib
  - example
  - ...
```
2. Write in the plugin's `pubspec.yaml`
```yaml
assets:
  - assets/libmy.js
  - assets/libmy.wasm
```
3. In the `init_web.dart` load `.js` **with** prefix `assets` and `.wasm` **without** this prefix:
```dart
...
import 'package:inject_js/inject_js.dart' as js;
...
const String _basePath = 'packages/my/assets';
...
  await js.importLibrary('assets/$_basePath/libmy.js');
  ...
  final wasmBinaries = (await rootBundle.load('$_basePath/libmy.wasm')).buffer.asUint8List();
  _module = await EmscriptenModule.compile(wasmBinaries, 'libmy');
...
```
